language: node_js
node_js:
  - 'node'
  - '7'
  - '6'

matrix:
  fast_finish: true

install:
  - npm install
  - npm link

before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
